package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            enabled = false
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }
    steps {
        insert(1) {
            maven {
                goals = "clean package"
                runnerArgs = "-Dmaven.test.failure.ignore=true -DskipTests"
            }
        }
        insert(2) {
            script {
                name = "Coverity"
                scriptContent = """
                    pwd;
                    cov-capture --project-dir ./;
                    cov-analyze --dir idir --webapp-security --disable-fb --export-summaries false;
                """.trimIndent()
            }
        }
    }
}
