package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Demo'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Demo")) {
    expectSteps {
        maven {
            name = "Initialize"
            goals = "clean package"
            runnerArgs = "-Dmaven.test.failure.ignore=true -DskipTests"
        }
        script {
            name = "Analyze"
            scriptContent = """
                pwd;
                cov-capture --project-dir ./;
                cov-analyze --dir idir --webapp-security --disable-fb --export-summaries false;
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            name = "Capture"
        }
    }
}
