package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SimpleJavaMavenApp_HttpsGithubComBryonglodencisspSimpleJavaMavenAppGitRefsHeadsMaster'
in the project with id = 'SimpleJavaMavenApp', and delete the patch script.
*/
create(RelativeId("SimpleJavaMavenApp"), GitVcsRoot({
    id("SimpleJavaMavenApp_HttpsGithubComBryonglodencisspSimpleJavaMavenAppGitRefsHeadsMaster")
    name = "https://github.com/bryonglodencissp/simple-java-maven-app.git#refs/heads/master"
    url = "https://github.com/bryonglodencissp/simple-java-maven-app.git"
    authMethod = password {
        userName = "bryonglodencissp"
        password = "credentialsJSON:bc6271b0-d473-49d6-82c0-f03516556891"
    }
}))

