#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
COVERITY_TOOL_HOME="/Applications/cov-analysis-macosx-2019.06"
PATH="$PATH:$COVERITY_TOOL_HOME/bin"

cov-run-desktop --config idir/conf.xml --dir idir --disconnected --text-output cov-errors.txt --exit1-if-defects true --present-in-reference false --set-new-defect-owner false --ignore-uncapturable-inputs true --strip-path `pwd` --all --disable-fb --analyze-scm-modified --scm git
if [ $? -eq 1 ]
then
	echo "cov-run-desktop found defects"
	echo "Stop the commit"
	exit 1
else
	echo "cov-run-desktop did not find defects"
	echo "Do not stop commit"
	exit 0
fi
